[package]
name = "dnstap-proxy-replay"
version = "0.1.0"
authors = ["Fastly"]
edition = "2018"
build = "src/build.rs"

[dependencies]
anyhow = "1.0.43"
async-channel = "1.6.1"
bytes = "1.0.1"
clap = "2.33.3"
extfmt = "0.1.1"
futures = "0.3.16"
hex = "0.4.3"
hyper = { version = "0.14.12", features = ["server", "http1", "tcp"] }
log = "0.4.14"
once_cell = "1.8.0"
prometheus = { version = "0.12.0" }
prost = "0.8.0"
simple-error = "0.2.3"
stderrlog = "0.5.1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.7"
tokio-util = { version = "0.6.7", features = ["codec", "io"] }

[build-dependencies]
prost-build = "0.8.0"
