[package]
name = "dnstap-utils"
version = "0.1.0"
description = "dnstap utilities"
authors = ["Fastly"]
keywords = ["dns", "dnstap"]
categories = ["command-line-utilities"]
edition = "2021"
repository = "https://github.com/fastly/dnstap-utils"
license = "BSD-3-Clause"
include = ["src/**/*", "LICENSE", "README.md", "dnstap.pb/dnstap.proto", "build.rs"]

[dependencies]
anyhow = "1.0.53"
async-channel = "1.6.1"
async-stream = "0.3.2"
bytes = "1.1.0"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.0.14", features = ["derive"] }
domain = "0.6.1"
extfmt = "0.1.1"
futures = "0.3.21"
futures-util = "0.3.21"
heck = "0.4.0"
hex = "0.4.3"
hyper = { version = "0.14.17", features = ["server", "stream", "http1", "tcp"] }
inotify = "0.10.0"
lazy_static = "1.4.0"
libc = "0.2.117"
log = "0.4.14"
prometheus = "0.13.0"
prometheus-static-metric = "0.5.1"
prost = "0.9.0"
simple-error = "0.2.3"
stderrlog = "0.5.1"
thiserror = "1.0.30"
tokio = { version = "1.16.1", features = ["full"] }
tokio-stream = "0.1.8"
tokio-util = { version = "0.7.0", features = ["codec", "io"] }

[build-dependencies]
prost-build = "0.9.0"
