[package]
name = "dnstap-utils"
version = "0.1.0"
authors = ["Fastly"]
edition = "2018"
repository = "https://github.com/fastly/dnstap-utils"
license = "BSD-3-Clause"

[dependencies]
anyhow = "1.0.43"
async-channel = "1.6.1"
async-stream = "0.3.2"
bytes = "1.0.1"
chrono = { version = "0.4.19", features = ["serde"] }
clap = "=3.0.0-beta.5"
domain = "0.6.1"
extfmt = "0.1.1"
futures = "0.3.16"
futures-util = "0.3.17"
heck = "0.3.3"
hex = "0.4.3"
hyper = { version = "0.14.12", features = ["server", "stream", "http1", "tcp"] }
inotify = "0.10.0"
lazy_static = "1.4.0"
libc = "0.2.107"
log = "0.4.14"
prometheus = { version = "0.12.0" }
prometheus-static-metric = "0.5.1"
prost = "0.8.0"
simple-error = "0.2.3"
stderrlog = "0.5.1"
thiserror = "1.0.28"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.7"
tokio-util = { version = "0.6.7", features = ["codec", "io"] }

[build-dependencies]
prost-build = "0.8.0"
